name: Go package

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Install cfssl
        run: |
          curl -s -L -o cfssl https://github.com/cloudflare/cfssl/releases/latest/download/cfssl_linux-amd64
          chmod +x cfssl
          sudo mv cfssl /usr/local/bin/cfssl
      
      - name: Build
        run: make build

      - name: Test
        run: CI=1 make test


